import {
  Box,
  Heading,
  Text,
  Stack,
  Container,
  Avatar,
  useColorModeValue,
  Flex,
  SimpleGrid,
  Icon,
} from '@chakra-ui/react';
import { FaQuoteLeft } from 'react-icons/fa';

const Testimonial = ({ children }) => {
  return (
    <Stack
      bg={useColorModeValue('white', 'gray.800')}
      boxShadow={'lg'}
      p={8}
      rounded={'xl'}
      align={'center'}
      pos={'relative'}
      _hover={{
        transform: 'translateY(-5px)',
        boxShadow: 'xl',
      }}
      transition="all 0.3s"
    >
      <Icon
        as={FaQuoteLeft}
        w={10}
        h={10}
        color={useColorModeValue('brand.200', 'brand.400')}
        opacity={0.2}
        position="absolute"
        top={4}
        left={4}
      />
      {children}
    </Stack>
  );
};

const TestimonialContent = ({ children }) => {
  return (
    <Stack
      textAlign={'center'}
      spacing={{ base: 5, md: 5 }}
      pt={10}
    >
      <Text
        fontSize={{ base: 'sm', md: 'md' }}
        textAlign={'center'}
        fontStyle="italic"
        color={useColorModeValue('gray.600', 'gray.400')}
      >
        {children}
      </Text>
    </Stack>
  );
};

const TestimonialHeading = ({ children }) => {
  return (
    <Heading as={'h3'} fontSize={'xl'}>
      {children}
    </Heading>
  );
};

const TestimonialAvatar = ({
  src,
  name,
  title,
}) => {
  return (
    <Flex align={'center'} mt={8} direction={'column'}>
      <Avatar
        src={src}
        mb={2}
        size="lg"
        border="2px solid"
        borderColor="brand.500"
      />
      <Stack spacing={-1} align={'center'}>
        <Text fontWeight={600}>{name}</Text>
        <Text fontSize={'sm'} color={useColorModeValue('gray.600', 'gray.400')}>
          {title}
        </Text>
      </Stack>
    </Flex>
  );
};

export default function Testimonials() {
  return (
    <Box py={16}>
      <Container maxW={'container.xl'} py={6} as={Stack} spacing={12}>
        <Stack spacing={0} align={'center'} mb={5}>
          <Heading color="brand.500">Meizie Users Love The Results</Heading>
          <Text color={'gray.500'} maxW="700px" textAlign="center">
            Our AI-powered captions are helping e-commerce businesses boost their sales and engagement
          </Text>
        </Stack>
        <SimpleGrid columns={{ base: 1, md: 3 }} spacing={10}>
          <Testimonial>
            <TestimonialContent>
              "Meizie has been a game-changer for our Shopify store. We've seen a 28% increase in conversions since we started using their AI captions for our product listings!"
            </TestimonialContent>
            <TestimonialAvatar
              src={'https://images.unsplash.com/photo-1586297135537-94bc9ba060aa?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&q=80&w=100&h=100'}
              name={'Sarah Johnson'}
              title={'Founder at StyleCorner'}
            />
          </Testimonial>
          
          <Testimonial>
            <TestimonialContent>
              "I was spending hours writing product captions that just weren't converting. With Meizie, I can generate dozens of high-quality captions in minutes, and they actually sell!"
            </TestimonialContent>
            <TestimonialAvatar
              src={'https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&q=80&w=100&h=100'}
              name={'Marcus Rodriguez'}
              title={'E-commerce Manager at TechGadgets'}
            />
          </Testimonial>
          
          <Testimonial>
            <TestimonialContent>
              "The captions generated by Meizie helped us increase our Instagram engagement by 45%. The AI understands exactly what will resonate with our audience and drive them to action."
            </TestimonialContent>
            <TestimonialAvatar
              src={'https://images.unsplash.com/photo-1494790108377-be9c29b29330?crop=entropy&cs=tinysrgb&fit=crop&fm=jpg&q=80&w=100&h=100'}
              name={'Jessica Chen'}
              title={'Social Media Director at FashionFusion'}
            />
          </Testimonial>
        </SimpleGrid>
      </Container>
    </Box>
  );
} 